version: '3.8'

services:
  # -----------------------------------------------------------------
  # 1. PHP Application (PHP-FPM)
  # -----------------------------------------------------------------
  app:
    # เราจะใช้ PHP-FPM image ซึ่งเหมาะกับการใช้คู่กับ Nginx
    image: php:8.3-fpm
    container_name: php-fpm-app
    # ติดตั้ง extension สำหรับ MySQL และอื่นๆ ที่จำเป็น
    # ถ้าคุณใช้ Laravel หรือ Framework อื่น ให้เพิ่ม extension ที่จำเป็นในนี้
    # ถ้าคุณใช้ Dockerfile ส่วนตัว ให้เปลี่ยน 'image' เป็น 'build: ./'
    command: docker-php-ext-install pdo pdo_mysql && docker-php-entrypoint php-fpm
    working_dir: /var/www/html
    volumes:
      # แมปโค้ดโปรเจกต์ของคุณ (./app) เข้าไปในคอนเทนเนอร์
      - ./app:/var/www/html
    environment:
      # ใช้ชื่อ service ของ MySQL เป็น DB_HOST
      DB_HOST: db
      DB_DATABASE: e_learning
      DB_USERNAME: root
      DB_PASSWORD: 1234
    networks:
      - app-network

  # -----------------------------------------------------------------
  # 2. Web Server (NGINX)
  # -----------------------------------------------------------------
  webserver:
    image: nginx:latest
    container_name: nginx-web
    ports:
      # เปิดพอร์ต 80 ของเครื่อง Host ไปยังพอร์ต 80 ของ Nginx
      - "80:80"
    volumes:
      - ./app:/var/www/html
      # จำเป็นต้องมีไฟล์ config สำหรับ Nginx เพื่อให้รู้จักกับ PHP-FPM
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  # -----------------------------------------------------------------
  # 3. Database (MySQL)
  # -----------------------------------------------------------------
  db:
    image: mysql:8.0
    container_name: mysql-server
    restart: always
    ports:
      # เปิดพอร์ต 3306 เผื่อไว้สำหรับการเชื่อมต่อจากภายนอก
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: e_learning
      # แนะนำให้ใช้ชื่อ User และ Password แยกต่างหาก
      # MYSQL_USER: user
      # MYSQL_PASSWORD: password
    volumes:
      # Persistent Data: เก็บข้อมูลไว้ในโฟลเดอร์ ./mysql_data/
      - ./mysql_data:/var/lib/mysql
    networks:
      - app-network

  # -----------------------------------------------------------------
  # 4. Database Management (phpMyAdmin)
  # -----------------------------------------------------------------
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-server
    restart: always
    ports:
      # เข้าถึง phpMyAdmin ที่ http://localhost:8080
      - "8080:80"
    environment:
      # PMA_HOST ต้องชี้ไปที่ชื่อ Service ของ Database (คือ 'db')
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
    depends_on:
      - db
    networks:
      - app-network

# -----------------------------------------------------------------
# 5. Networks Section
# -----------------------------------------------------------------
networks:
  app-network:
    driver: bridge
